### ISSUE TITLE
Search button styling

### ISSUE THREAD

**Issue by Priyami** [Priyami/weatherapp#4]
- Style change is needed for the Search button. 
- visibility of the click event is missing.

**Comment by rkoleci** [comment]
Hello,

I am new to contribution on Open source. Would like to take on this issue. 
Can you assign it to me please ?

Thanks

**Comment by Priyami** [comment]
Hello @rkoleci ,

Thank you for contributing. Please let me know any questions regarding the code.

**Comment by rkoleci** [comment]
Thanks. 

What style do you need exactly ?

**Comment by Priyami** [comment]
Right now, I am using `faSearchin` icon type from `react-icons` package to display the (magnifying glass) search button near input field.

** Requirement**

-  When you hover on search button,  animated flash for the background.
-  When you click on search button, add the button pressed effect (up and down motion)

**Comment by rkoleci** [comment]
Think i got it. Will try to fix these asap.

**Comment by rkoleci** [comment]
Create a PR for this.

Added the pressed/unpressed button effect, color.
Also formatted the code. 

Thanks!

**Comment by Priyami** [comment]
Thank you! @rkoleci. May I know what's the standard requirement to format the code?

**Comment by rkoleci** [comment]
Usualla a shortcut is enough as vd code comes with its own formatter. Shift alt f
Cmd f

You can use extensions like Prettier for more customization.
