### ISSUE TITLE
More Details Button functionality

### ISSUE THREAD

**Issue by Priyami** [Priyami/weatherapp#8]
- Shows the 3 days weather of default Boston.
- Need to change 3 days' weather when you search for any other city by suggestion.

**Comment by rkoleci** [comment]
Hello,

I am new to contribution on Open source. Would like to take on this issue.
Can you assign it to me please ?

Thanks

**Comment by Priyami** [comment]
Hello @rkoleci ,

I worked on this issue. I think I solved it.  Three days' weather displayed of any other city by suggestions list clicked. 

<img width="1178" alt="3dayweather" src="https://user-images.githubusercontent.com/4775877/142769047-dbbae3b9-f09a-4e47-9f69-98358c92b1fe.png">

But it has another issue, "Sunday" is not displaying. In our weather API, we get the `date (yyyy-mm-dd)` format. not the day[Sun, Mon, Tue,...] of the date. So I have manipulated using the `dayDate(date)` function to get a specific day of date in `Weekweather.js`.

If you have any other suggestions for the above issue, Please let me know.

**Comment by rkoleci** [comment]
Sure, i will check it out.

Good thing the data is in response. 
Commit your changes and I will check it out.

**Comment by rkoleci** [comment]
Fixed it check it out.
